package com.android.publiccourse;

public enum TaskType {
	Meos_Ex, Get_User_Block_Info, Add_User_Action_Count, 
	Update_User_Sex, Update_User_Address, Update_User_Email, 
	Update_User_PhoneNumber, Update_User_Introduce, Update_User_NickName, 
	Get_User_Score_List, Add_User_Visit_Record, Add_User_Score, 
	Handle_Friend_Relation, Delete_Friend_Request, Add_Friend_Request, 
	Get_Friend_Deital_By_UserID, Get_Friend_By_Name, Get_Friend_By_Condition,
	Get_Friend_List, Get_Friend_EducationNotice_Detail, 
	Get_Friend_EducationNotice, Get_Friend_MyFavorite, Save_Friend_Detail,
	Get_Friend_Detail, Get_Friend_HomePage, Ob_Check_Version,Ob_Auto_Check_Version,
	User_Login,  User_Regist,Get_Course_List,Get_Pub_Course_List, 
	Get_Public_Courses, Get_Public_HotCourses,Get_Public_SearchCourses,
	Pub_Theme,Get_Colleges_And_Subjects, Get_Course_Video_List,
	Get_Course_DocList, Get_Course_Doc_PDF_List, Get_Course_Notice_List,
	Get_Course_Notice_PDF_List, Get_Course_Exam_Task_List, 
	Set_Courseware_Study_Status, Set_Courseware_Study_Point,
	Get_Course_Exam_Task_Item, Save_UnFinish_Exam_Task_Result, 
	Submit_Objective_Exam_Result, Get_Course_Exam_Task_ByID, 
	Submit_User_Feedback, Add_Course_Click_Time, Add_Course_Total_Time, 
	Get_Obs_Login,Get_Theme_List,Get_NOTCategory_Theme_List,
	Get_Theme_Category,Get_Theme_Class, Get_Theme_Detail_By_Theme_Id, 
	Get_Speak_List_By_Theme_Id, Add_Attention_Of_Theme, 
	Cancel_Attention_Of_Theme, Add_Speak_Content, Get_Speak_Detail_By_Speak_Id,
	Get_Review_List_By_Speak_Id, Delete_Speak_By_SpeakId, 
	Delete_Review_By_ReviewId, Add_Support_Speak, Add_Favorite_Speak, 
	Delete_Favorite_Speak, Add_Review_Of_Speak, Add_RevertOfReview,
	Get_Theme_Author_Detail, Get_Theme_list_By_Author, 
	Get_Theme_list_By_User, Get_Speak_List_By_User, Get_Comment_List_By_User,
	Get_Favor_List_By_User, Get_User_No_Speakinfo, 
	Edit_Speak_Content, Edit_Comment_Content, Show_Course,
	Add_Comment_For_Course, Get_Comments, Rank_Course, 
	Add_Course_Playing_Count, Add_Course_View_Count, Public_Course_Login, 
	Public_Course_Logout
}
